### ISSUE TITLE
pytest_runtest_makereport unignorable error for item.funcargs

### ISSUE THREAD

**Issue by voobel** [dbader/pytest-mypy#135]
I have such `pytest_runtest_makereport` for adding Playwright failure screenshots to `pytest-html` logs:
```
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item):
    callers = yield
    report = callers.get_result()
    report.extra = []
    if report.when == "call":
        xfail = hasattr(report, "wasxfail")
        if ((report.skipped and xfail) or (report.failed and not xfail)) and "page" in item.funcargs:
            page = item.funcargs["page"]
            screenshot = base64.b64encode(page.screenshot()).decode()
            pytest_html = item.config.pluginmanager.getplugin("html")
            report.extra.append(pytest_html.extras.png(screenshot))
```

It complains following: `INTERNALERROR> AttributeError: 'MypyStatusItem' object has no attribute 'funcargs'`
Indeed, `item` doesn't have `funcargs` attribute but it's added there on test runtime. Funnily enough I can't also ignore those errors with `# type: ignore` in-line comment nor file-level comment.

If all `mypy` checks pass, then I don't get this error, but if there are any, then this error hides them all, and I have to comment this method out to see the real errors.

Is there some other way to access `page` for taking screenshot, without using `item.funcargs`?
Or is there some method to ignore those `INTERNALERROR`s, or `AttributeError`s? I tried from `mypy.ini` also, but always same results. Only when I set globally `ignore_errors = True` it won't complain, but then `mypy` doesn't do anything useful obviously.

**Comment by voobel** [comment]
Versions in case it matters:
```
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/ubuntu/tg-test, configfile: pytest.ini, testpaths: tests
plugins: allure-pytest-2.9.45, playwright-0.3.0, html-3.1.1, mypy-0.9.1, metadata-2.0.1, Faker-13.6.0, base-url-2.0.0
```

**Comment by dmtucker** [comment]
> `item` doesn't have `funcargs` attribute

I think this is the crux of the issue. `pytest_runtest_makereport` accepts a `pytest.Item`. [The `funcargs` attribute is only defined for `pytest.Function`s.](https://github.com/pytest-dev/pytest/blob/04be900d0677791d97e955b42440627b1818fbcb/src/_pytest/python.py#L1746) All `pytest.Function`s are `pytest.Item`s, but not all `pytest.Item`s are `pytest.Function`s (e.g. `MypyStatusItem`).

Could you add a check for `pytest.Function`s?
``` python
    if report.when == "call" and isinstance(item, pytest.Function):
```
Or, maybe you could equate a missing `funcargs` attribute with `page` not being present:
``` python
        if ... and "page" in getattr(item, "funcargs", {}):
```
