### ISSUE TITLE
--silent-imports flag?

### ISSUE THREAD

**Issue by AndreaCrotti** [dbader/pytest-mypy#2]
I normally have to pass the --silent-imports flag, to mypy to avoid all sort of errors.
This plugin at the moment doesn't let any extra flag to be passed to mypy though, is that correct?

**Comment by dbader** [comment]
There's a stub for passing through command line arguments but I haven't spent a lot of time on this project lately: https://github.com/dbader/pytest-mypy/blob/f512099fb62b2e77e9d1496b9201d5dcbbfcb4e0/pytest_mypy.py#L50-L52

Another workaround would be configuring `mypy` through its ini file.

By the way, if anyone wants to jump on adding command line flag passthrough, I can provide some guidance / review.
