### ISSUE TITLE
Allow passing of --check-untyped-defs

### ISSUE THREAD

**Issue by gappleto97** [dbader/pytest-mypy#20]
It would be nice if I could pass this option to mypy through your plugin

**Comment by dmtucker** [comment]
@gappleto97 In 0.4.0, you should be able to pass any option through via a hook in `conftest.py`:
https://github.com/dbader/pytest-mypy/blob/7d17270a910dce38ae1168e2fc36c395d8fe4956/README.rst#L47-L49
