### ISSUE TITLE
Still slow

### ISSUE THREAD

**Issue by johnarnold** [dbader/pytest-mypy#21]
Even with the change to invoke with --incremental, this plugin is still really slow:

```
time mypy net_devices2

real    0m3.822s
user    0m3.724s
sys     0m0.092s

```
```
time pytest --mypy net_devices2

real    2m54.786s
user    2m52.424s
sys     0m1.944s
```

mypy==0.620
pytest==3.4.1
pytest-cov==2.5.1
pytest-forked==0.2
pytest-mypy==0.3.2
pytest-xdist==1.22.5

**Comment by nmatthews-asapp** [comment]
I have also noticed this. Any updates?

**Comment by dmtucker** [comment]
0.4.0 will make a single invocation per-session (instead of per-file) 🏎
