### ISSUE TITLE
`mypy_path` option or `MYPYPATH` is not respected?

### ISSUE THREAD

**Issue by naoko** [dbader/pytest-mypy#5]
I have mypy.ini and have 2 global falgs
```
[mypy]
ignore_missing_imports = yes
mypy_path = src
```

Certainly ignore_missing_imports flags works but mypy gets always run for tests directory.
I tried to set `export MYPYPATH=src` but no luck.

Looking at
```
def pytest_collect_file(path, parent):
    config = parent.config
    if config.option.mypy and path.ext == '.py':
        return MypyItem(path, parent)
```
It appears to me `path` is from `testpaths` under `pytest.ini`
So to solve my problem (to run mypy on src code), I've added src addition to tests dir as follows
```
[pytest]
testpaths =
    tests src
```
Is this expected behavior?

**Comment by mpaolini** [comment]
try using

```
[mypy-tests*]
ignore_errors = True
```
in your setup.cfg or pytest.ini

as per https://mypy.readthedocs.io/en/latest/config_file.html#per-module-flags

**Comment by dmtucker** [comment]
This appears to be resolved. Feel free to reopen if it isn't.
