### ISSUE TITLE
required argument 'flush_errors' error with latest version of mypy

### ISSUE THREAD

**Issue by macheins** [dbader/pytest-mypy#6]
Hi @dbader,

`pytest-mypy` seems to be broken with the latest release of `mypy==0.570`, but I did not yet have the time to investigate it further or fix it. It yields the following errors for each file:

```
[...]: in runtest
    res = mypy.main.type_check_only(sources, None, options)
E   TypeError: type_check_only() missing 1 required positional argument: 'flush_errors'
```

**Comment by jniedrauer** [comment]
My builds using pytest-mypy are now failing with the same error message:

```.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py:617: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
.tox/py36/lib/python3.6/site-packages/_pytest/runner.py:106: in pytest_runtest_call
    item.runtest()
.tox/py36/lib/python3.6/site-packages/pytest_mypy.py:58: in runtest
    res = mypy.main.type_check_only(sources, None, options)
E   TypeError: type_check_only() missing 1 required positional argument: 'flush_errors'```

**Comment by petr-muller** [comment]
See this PR in mypy for the breaking change: https://github.com/python/mypy/pull/4396

I've submitted a PR here that makes the errors go away and does not seem to break anything. "Proper" investigation into the mypy PR might be needed, but I did not have capacity for that :(

**Comment by marcintustin** [comment]
Please can we get @petr-muller's PR merged and a new release out? https://github.com/dbader/pytest-mypy/pull/7

**Comment by kennethreitz** [comment]
need this
