### ISSUE TITLE
Add support settings from setup.cfg

### ISSUE THREAD

**Issue by pbelskiy** [dbader/pytest-mypy#87]
Hello, thanks for your package, but could you please add support to read settings from mypy related section from setup.cfg because many python machinery tools do so, and I don't like to have a lot of different config files in root of my repo. ✌️

**Comment by dmtucker** [comment]
That should be supported (i.e. you should be able to use any [configuration file supported by Mypy](https://mypy.readthedocs.io/en/latest/config_file.html?highlight=setup.cfg#the-mypy-configuration-file)) :thinking: 

Is something not working as expected?

**Comment by pbelskiy** [comment]
How can I pass config file path? mypy has --config-file but, how to use it throught pytest-mypy plugin?
